version: "1.1"

services:
  3xui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    restart: unless-stopped

    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_ENABLE_FAIL2BAN: "true"

    ports:
      - "2053:2053/tcp"
      - "30000:30000/tcp"
      - "30000:30000/udp"
      - "30001:30001/tcp"
      - "30001:30001/udp"
      - "30002:30002/tcp"
      - "30002:30002/udp"
